/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "outline-variant": "#3e4850",
        "on-primary-fixed": "#001e2f",
        "tertiary": "#ffb95f",
        "surface": "#0b1326",
        "secondary": "#4edea3",
        "surface-variant": "#2d3449",
        "surface-container": "#171f33",
        "inverse-surface": "#dae2fd",
        "error-container": "#93000a",
        "tertiary-fixed": "#ffddb8",
        "on-surface": "#dae2fd",
        "background": "#0b1326",
        "surface-bright": "#31394d",
        "on-secondary-container": "#00311f",
        "on-tertiary": "#472a00",
        "on-primary": "#00344d",
        "primary-fixed": "#c9e6ff",
        "on-secondary-fixed-variant": "#005236",
        "on-primary-fixed-variant": "#004c6e",
        "on-secondary": "#003824",
        "secondary-fixed": "#6ffbbe",
        "secondary-container": "#00a572",
        "tertiary-fixed-dim": "#ffb95f",
        "surface-dim": "#0b1326",
        "on-tertiary-fixed": "#2a1700",
        "on-tertiary-container": "#4a2c00",
        "on-secondary-fixed": "#002113",
        "outline": "#88929b",
        "on-background": "#dae2fd",
        "secondary-fixed-dim": "#4edea3",
        "surface-container-high": "#222a3d",
        "primary-fixed-dim": "#89ceff",
        "inverse-primary": "#006591",
        "inverse-on-surface": "#283044",
        "surface-container-highest": "#2d3449",
        "primary-container": "#0ea5e9",
        "surface-container-low": "#131b2e",
        "on-primary-container": "#003751",
        "error": "#ffb4ab",
        "primary": "#89ceff",
        "on-error-container": "#ffdad6",
        "surface-tint": "#89ceff",
        "on-surface-variant": "#bec8d2",
        "on-tertiary-fixed-variant": "#653e00",
        "on-error": "#690005",
        "tertiary-container": "#d88a00",
        "surface-container-lowest": "#060e20"
      },
      borderRadius: { "DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem" },
      spacing: { "sm": "12px", "container-max": "1440px", "xs": "8px", "gutter": "24px", "lg": "32px", "xl": "48px", "md": "20px", "base": "4px" },
      fontFamily: { "headline-xl": ["Hanken Grotesk"], "headline-lg": ["Hanken Grotesk"], "label-caps": ["JetBrains Mono"], "body-md": ["Inter"], "data-mono": ["JetBrains Mono"], "body-sm": ["Inter"], "body-lg": ["Inter"], "headline-md": ["Hanken Grotesk"] },
      fontSize: {
        "headline-xl": ["40px", {"lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "fontWeight": "600"}],
        "label-caps": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "700"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "data-mono": ["14px", {"lineHeight": "20px", "letterSpacing": "-0.01em", "fontWeight": "500"}],
        "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
}